# Generated by Django 5.2.5 on 2025-09-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscription_trial_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('trial', 'Free Trial'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='trial', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['subscription_code'], name='subscriptio_subscri_6d42c5_idx'),
        ),
    ]
