# Generated by Django 5.2.5 on 2025-09-01 21:31

import django.utils.timezone
import subscriptions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscription_amount_subscription_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='trial_end',
            field=models.DateTimeField(blank=True, default=subscriptions.models.default_trial_end, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='trial_start',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
