# Generated by Django 5.2.5 on 2025-10-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_alter_paymentmethod_options_paymentmethod_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='trialing', max_length=20),
        ),
    ]
